### ISSUE TITLE
Fetching most recent posts

### ISSUE THREAD

**Issue by adamdejl** [ic-drp02/drp-server#9]
API for fetching a specified number of the most recently added posts

**Comment by hasali19** [comment]
@pranavmangal Did you get anywhere with this?

I was thinking we should probably implement some kind of pagination api for things like posts and questions. For reference, I've implemented something like this [here](https://github.com/hasali19/speedy/blob/b742d4beb8c27cb1ad9a89c7d96712655e21b847/src/handlers.rs#L54), albeit in rust.
